import os
import json
import torch
import joblib
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from lightgbm import Booster
from catboost import CatBoostRegressor

# Import PyTorch classes from our utils file
from inference_utils import LSTMModel, GRUModel, TransformerModel, NBeatsModel, TFTModel

# Configuration
MODELS_DIR = './models'
RESULTS_DIR = './results'
DATA_DIR = './data'

SEQ_LENGTH = 10
HIDDEN_SIZE = 32

def get_top_models(commodity, horizon, top_n=3):
    """Reads the JSON metrics and returns the top N models based on Directional Accuracy."""
    ml_path = os.path.join(RESULTS_DIR, f'stage2_ml_metrics_{horizon}d.json')
    dl_path = os.path.join(RESULTS_DIR, f'stage2_dl_metrics_{horizon}d.json')
    
    if not os.path.exists(ml_path) or not os.path.exists(dl_path):
        raise ValueError(f"Metrics not found for horizon {horizon}d. Did you run the training loop?")
        
    with open(ml_path, 'r') as f:
        ml_data = json.load(f)
    with open(dl_path, 'r') as f:
        dl_data = json.load(f)
        
    all_models = {}
    
    # ML Models
    if commodity in ml_data:
        for model_name, metrics in ml_data[commodity].items():
            all_models[model_name] = metrics['Dir_Acc']
            
    # DL Models
    if commodity in dl_data:
        for model_name, metrics in dl_data[commodity].items():
            all_models[model_name] = metrics['Dir_Acc']
            
    if not all_models:
        raise ValueError(f"Commodity {commodity} not found in metrics files.")
        
    # Sort models by Directional Accuracy descending
    sorted_models = sorted(all_models.items(), key=lambda item: item[1], reverse=True)
    return sorted_models[:top_n]

def prepare_data(commodity, horizon):
    """Loads CSV data, extracts the final features, and prepares inputs for ML and DL."""
    file_path = os.path.join(DATA_DIR, f"{commodity}.csv")
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Data for {commodity} not found.")
        
    df = pd.read_csv(file_path, index_col='Date', parse_dates=True)
    # Forward fill any NaNs to prevent crashes
    df = df.ffill()
    
    drop_cols = ['Target_Close_Next', 'Target_Return_Next', 'Target_Direction', 
                 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']
    features = [col for col in df.columns if col not in drop_cols]
    
    # Drop any targets generated by horizon shifting
    features = [col for col in features if not col.startswith('Target_')]
    
    current_price = df['Close'].iloc[-1]
    
    X_raw = df[features].values
    
    # ML Input (1D vector of the very last row)
    X_ml = X_raw[-1:]
    
    # DL Input (Sequences of last SEQ_LENGTH rows)
    X_dl_raw = X_raw[-SEQ_LENGTH:]
    
    # If we don't have enough data for a sequence, we cannot run DL models.
    if len(X_dl_raw) < SEQ_LENGTH:
        raise ValueError(f"Not enough data to create a sequence of length {SEQ_LENGTH}")
        
    # Load Scaler
    scaler_path = os.path.join(MODELS_DIR, f'{commodity}_scaler_{horizon}d.pkl')
    # Fallback to general scaler if horizon-specific doesn't exist
    if not os.path.exists(scaler_path):
        scaler_path = os.path.join(MODELS_DIR, f'{commodity}_scaler.pkl')
        
    scaler = joblib.load(scaler_path)
    X_dl_scaled = scaler.transform(X_dl_raw)
    
    # Add batch dimension [1, 10, num_features]
    X_dl_tensor = torch.tensor(X_dl_scaled, dtype=torch.float32).unsqueeze(0)
    
    return X_ml, X_dl_tensor, len(features), current_price, features

def load_and_predict(model_name, commodity, horizon, X_ml, X_dl_tensor, input_size):
    """Loads the specific artifact from disk and predicts the return."""
    device = torch.device('cpu')
    pred_return = None
    
    # XGBoost
    if model_name == 'XGBoost':
        model = XGBRegressor()
        model.load_model(os.path.join(MODELS_DIR, f'{commodity}_xgboost_{horizon}d.json'))
        pred_return = model.predict(X_ml)[0]
        
    # LightGBM
    elif model_name == 'LightGBM':
        model = Booster(model_file=os.path.join(MODELS_DIR, f'{commodity}_lightgbm_{horizon}d.txt'))
        pred_return = model.predict(X_ml)[0]
        
    # CatBoost
    elif model_name == 'CatBoost':
        model = CatBoostRegressor()
        model.load_model(os.path.join(MODELS_DIR, f'{commodity}_catboost_{horizon}d.cbm'))
        pred_return = model.predict(X_ml)[0]
        
    # RandomForest
    elif model_name == 'RandomForest':
        model = joblib.load(os.path.join(MODELS_DIR, f'{commodity}_randomforest_{horizon}d.pkl'))
        pred_return = model.predict(X_ml)[0]
        
    # Deep Learning PyTorch Models
    else:
        if model_name == 'LSTM':
            model = LSTMModel(input_size, HIDDEN_SIZE)
        elif model_name == 'GRU':
            model = GRUModel(input_size, HIDDEN_SIZE)
        elif model_name == 'Transformer':
            model = TransformerModel(input_size, HIDDEN_SIZE)
        elif model_name == 'N-BEATS':
            model = NBeatsModel(SEQ_LENGTH, input_size)
        elif model_name == 'TFT':
            model = TFTModel(input_size, HIDDEN_SIZE)
        else:
            raise ValueError(f"Unknown model architecture: {model_name}")
            
        model_path = os.path.join(MODELS_DIR, f'{commodity}_{model_name.lower().replace("-","")}_{horizon}d.pt')
        model.load_state_dict(torch.load(model_path, map_location=device))
        model.eval()
        with torch.no_grad():
            pred_return = model(X_dl_tensor).squeeze().item()
            
    return pred_return

def ensemble_predict(commodity, horizon, top_n=3):
    """
    Main function: gets top models, processes data, runs inferences, and computes accuracy-weighted average.
    """
    # 1. Get Top Models
    top_models = get_top_models(commodity, horizon, top_n)
    print(f"\\n{'='*50}\\nENSEMBLE INFERENCE: {commodity.upper()} ({horizon}-Day)\\n{'='*50}")
    print(f"Selected Top {top_n} Models Based on Directional Accuracy:")
    for m, acc in top_models:
        print(f" - {m}: {acc}%")
        
    # 2. Prepare Data
    X_ml, X_dl_tensor, input_size, current_price, _ = prepare_data(commodity, horizon)
    print(f"Current Price (Today): ${current_price:.4f}")
    
    # 3. Run Inference
    total_weight = 0
    weighted_return = 0
    predictions = {}
    
    for model_name, acc in top_models:
        try:
            pred_ret = load_and_predict(model_name, commodity, horizon, X_ml, X_dl_tensor, input_size)
            predictions[model_name] = pred_ret
            # Weight is the historical accuracy
            weighted_return += pred_ret * acc
            total_weight += acc
            print(f"[{model_name}] Predicted Return: {pred_ret:.4f} (Implied Price: ${current_price * (1 + pred_ret):.4f})")
        except Exception as e:
            print(f"⚠️ Error loading {model_name}: {str(e)}")
            continue
            
    # 4. Math Consensus
    if total_weight == 0:
        raise RuntimeError("Ensemble failed: No models were successfully loaded.")
        
    final_return = weighted_return / total_weight
    final_price = current_price * (1 + final_return)
    direction = "UP 🟢" if final_return > 0 else "DOWN 🔴"
    
    print(f"\\n✅ FINAL ENSEMBLE PREDICTION ({horizon} Days Out)")
    print(f"Consensus Return : {final_return * 100:.2f}%")
    print(f"Target Price     : ${final_price:.4f}")
    print(f"Direction        : {direction}")
    
    return {
        'commodity': commodity,
        'horizon': horizon,
        'current_price': current_price,
        'predicted_price': final_price,
        'predicted_return': final_return,
        'direction': direction,
        'models_used': [m[0] for m in top_models]
    }

if __name__ == "__main__":
    # Test Block: Run an ensemble for Gold (60-day horizon) and Natural Gas (14-day horizon)
    print("Running Ensemble Backend Test...")
    ensemble_predict('gold', 60, top_n=3)
    ensemble_predict('natural_gas', 14, top_n=2)
    ensemble_predict('crude_oil', 120, top_n=3)
